-- Migration: Add tags support to endpoints and tokens
-- Run this script if you have an existing database without tags

-- Create TAGS table
CREATE TABLE IF NOT EXISTS API_PROXY.APP.TAGS (
    TAG_ID VARCHAR(36) DEFAULT UUID_STRING(),
    NAME VARCHAR(100) NOT NULL UNIQUE,
    COLOR VARCHAR(7), -- Hex color code (e.g., #FF5733)
    DESCRIPTION VARCHAR(500),
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(255)
)
CLUSTER BY (NAME);

-- Create ENDPOINT_TAGS junction table
CREATE TABLE IF NOT EXISTS API_PROXY.APP.ENDPOINT_TAGS (
    ENDPOINT_ID VARCHAR(36) NOT NULL,
    TAG_ID VARCHAR(36) NOT NULL,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ENDPOINT_ID, TAG_ID)
)
CLUSTER BY (ENDPOINT_ID, TAG_ID);

-- Create TOKEN_TAGS junction table
CREATE TABLE IF NOT EXISTS API_PROXY.APP.TOKEN_TAGS (
    TOKEN_ID VARCHAR(36) NOT NULL,
    TAG_ID VARCHAR(36) NOT NULL,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TOKEN_ID, TAG_ID)
)
CLUSTER BY (TOKEN_ID, TAG_ID);

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE API_PROXY.APP.TAGS TO ROLE API_PROXY_SERVICE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE API_PROXY.APP.ENDPOINT_TAGS TO ROLE API_PROXY_SERVICE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE API_PROXY.APP.TOKEN_TAGS TO ROLE API_PROXY_SERVICE_ROLE;

