-- =====================================================
-- Snowflake API Proxy Service - Quick Setup
-- =====================================================
-- Simplified script for quick service account setup
-- Run this as ACCOUNTADMIN or SYSADMIN
--
-- Usage:
--   Option 1 (Automated): Use scripts/deploy.sh - it runs setup automatically
--   Option 2 (Manual): Run this for a quick setup, then sql/create_tables.sql
--
-- Creates same resources as setup_service_account.sql but with fewer options.
-- Uses schema "APP" (not PUBLIC) to align with deploy.sh and create_tables.sql.
--
-- =====================================================

-- Set context
USE ROLE ACCOUNTADMIN;

-- 1. Create database and schema (first, so they exist for user DEFAULT_NAMESPACE)
CREATE DATABASE IF NOT EXISTS API_PROXY;
CREATE SCHEMA IF NOT EXISTS API_PROXY.APP;

-- 2. Create warehouse
CREATE WAREHOUSE IF NOT EXISTS API_PROXY_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- 3. Create service role
CREATE ROLE IF NOT EXISTS API_PROXY_SERVICE_ROLE
  COMMENT = 'Role for Snowflake API Proxy Service';

-- 4. Create service user (database and schema now exist for DEFAULT_NAMESPACE)
CREATE USER IF NOT EXISTS API_PROXY_SERVICE_USER
  PASSWORD = 'ChangeThisPassword123!'
  LOGIN_NAME = 'API_PROXY_SERVICE_USER'
  DISPLAY_NAME = 'API Proxy Service User'
  EMAIL = 'api-proxy-service@yourcompany.com'
  MUST_CHANGE_PASSWORD = FALSE
  DISABLED = FALSE
  DEFAULT_WAREHOUSE = 'API_PROXY_WH'
  DEFAULT_ROLE = 'API_PROXY_SERVICE_ROLE'
  DEFAULT_NAMESPACE = 'API_PROXY.APP'
  COMMENT = 'Service account for Snowflake API Proxy Service';

-- 5. Grant basic permissions
GRANT USAGE ON WAREHOUSE API_PROXY_WH TO ROLE API_PROXY_SERVICE_ROLE;
GRANT USAGE ON DATABASE API_PROXY TO ROLE API_PROXY_SERVICE_ROLE;
GRANT USAGE ON SCHEMA API_PROXY.APP TO ROLE API_PROXY_SERVICE_ROLE;
GRANT CREATE TABLE ON SCHEMA API_PROXY.APP TO ROLE API_PROXY_SERVICE_ROLE;
GRANT CREATE STAGE ON SCHEMA API_PROXY.APP TO ROLE API_PROXY_SERVICE_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA API_PROXY.APP TO ROLE API_PROXY_SERVICE_ROLE;
GRANT CREATE FUNCTION ON SCHEMA API_PROXY.APP TO ROLE API_PROXY_SERVICE_ROLE;

-- 6. Grant data access permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA API_PROXY.APP TO ROLE API_PROXY_SERVICE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA API_PROXY.APP TO ROLE API_PROXY_SERVICE_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA API_PROXY.APP TO ROLE API_PROXY_SERVICE_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA API_PROXY.APP TO ROLE API_PROXY_SERVICE_ROLE;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA API_PROXY.APP TO ROLE API_PROXY_SERVICE_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA API_PROXY.APP TO ROLE API_PROXY_SERVICE_ROLE;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA API_PROXY.APP TO ROLE API_PROXY_SERVICE_ROLE;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA API_PROXY.APP TO ROLE API_PROXY_SERVICE_ROLE;

-- 7. Assign role to user and SYSADMIN
GRANT ROLE API_PROXY_SERVICE_ROLE TO USER API_PROXY_SERVICE_USER;

-- Grant the service role to SYSADMIN for management purposes
GRANT ROLE API_PROXY_SERVICE_ROLE TO ROLE SYSADMIN;

ALTER USER API_PROXY_SERVICE_USER SET DEFAULT_ROLE = 'API_PROXY_SERVICE_ROLE';
-- Note: DEFAULT_WAREHOUSE and DEFAULT_NAMESPACE are already set in CREATE USER above

-- 9. Display connection information
SELECT 
    'Setup Complete!' AS STATUS,
    'Username: API_PROXY_SERVICE_USER' AS USERNAME,
    'Password: ChangeThisPassword123!' AS PASSWORD,
    'Role: API_PROXY_SERVICE_ROLE' AS ROLE,
    'Database: API_PROXY' AS DATABASE,
    'Schema: APP' AS SCHEMA,
    'Warehouse: API_PROXY_WH' AS WAREHOUSE;
