-- =====================================================
-- One-time script to rename tables in existing database
-- Run this BEFORE running cleanup.sh and deploy.sh
-- Or use this if you want to keep your existing data
-- =====================================================

USE DATABASE API_PROXY;
USE SCHEMA APP;

-- Rename PAT_TOKENS to API_KEYS
ALTER TABLE PAT_TOKENS RENAME TO API_KEYS;

-- Rename TOKEN_USAGE_LOG to API_USAGE_LOG
ALTER TABLE TOKEN_USAGE_LOG RENAME TO API_USAGE_LOG;

-- Update views
CREATE OR REPLACE VIEW ENDPOINTS_WITH_TOKENS AS
SELECT 
    e.ENDPOINT_ID,
    e.NAME,
    e.DESCRIPTION,
    e.TYPE,
    e.TARGET,
    e.METHOD,
    e.IS_ACTIVE,
    e.CREATED_AT,
    e.UPDATED_AT,
    e.CREATED_BY,
    CASE WHEN k.TOKEN_ID IS NOT NULL THEN TRUE ELSE FALSE END AS HAS_TOKEN,
    k.TOKEN_ID,
    k.LAST_USED AS TOKEN_LAST_USED,
    k.USAGE_COUNT AS TOKEN_USAGE_COUNT
FROM ENDPOINTS e
LEFT JOIN API_KEYS k ON e.ENDPOINT_ID = k.ENDPOINT_ID AND k.IS_ACTIVE = TRUE;

CREATE OR REPLACE VIEW ENDPOINT_STATISTICS AS
SELECT 
    e.ENDPOINT_ID,
    e.NAME,
    e.TYPE,
    e.IS_ACTIVE,
    COUNT(DISTINCT k.TOKEN_ID) AS TOKEN_COUNT,
    SUM(k.USAGE_COUNT) AS TOTAL_REQUESTS,
    MAX(k.LAST_USED) AS LAST_REQUEST_TIME
FROM ENDPOINTS e
LEFT JOIN API_KEYS k ON e.ENDPOINT_ID = k.ENDPOINT_ID AND k.IS_ACTIVE = TRUE
GROUP BY e.ENDPOINT_ID, e.NAME, e.TYPE, e.IS_ACTIVE;

CREATE OR REPLACE VIEW TOKEN_USAGE_STATS AS
SELECT 
    TOKEN_ID,
    ENDPOINT_ID,
    SUM(REQUEST_COUNT) AS TOTAL_REQUESTS,
    MAX(LAST_USED) AS LAST_USED,
    COUNT(DISTINCT DATE(LAST_USED)) AS ACTIVE_DAYS
FROM API_USAGE_LOG
WHERE LAST_USED >= DATEADD(DAY, -30, CURRENT_TIMESTAMP())
GROUP BY TOKEN_ID, ENDPOINT_ID
ORDER BY TOTAL_REQUESTS DESC;

-- Update permissions
REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLE API_PROXY.APP.PAT_TOKENS FROM ROLE API_PROXY_SERVICE_ROLE;
REVOKE SELECT, INSERT, UPDATE ON TABLE API_PROXY.APP.TOKEN_USAGE_LOG FROM ROLE API_PROXY_SERVICE_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE API_PROXY.APP.API_KEYS TO ROLE API_PROXY_SERVICE_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE API_PROXY.APP.API_USAGE_LOG TO ROLE API_PROXY_SERVICE_ROLE;

